sprint_3
ionetek/middle.messenger.praktikum.yandex pull request #6
Opened 2022-07-07 14:43 UTC by ionetek

Sprint 3

2022-07-07 17:10 UTC, podlovchenko requested changes
Привет, по работе системы все хорошо, получилось очень симпатичное приложение)

В коде много используется @ts-ignore, это плохая практика, преимущества типизирования теряются, постарайся избавиться)

Также про выключение правил eslint

2022-07-07 17:10 UTC, podlovchenko commented on package.json
> +    "uuid": "^8.3.2"
Лучше задавать фиксированные версии зависимостям

Если вы однажды решите, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам. Плюс никогда не знаешь в какой версии появляется та или иная уязвимость

2022-07-07 17:10 UTC, podlovchenko commented on src/components/button/Button.ts
> +    }
Такую запись можно сократить
```suggestion
    const className = this.props.className ?? '';
```
либо
```suggestion
    const {className = ''} = this.props;
```
и лучше давать более понятные названия переменным

2022-07-07 17:10 UTC, podlovchenko commented on src/components/chatlist/ChatList.css
> +    /*height: calc( 100% - 160px);*/
Комментарии в коде лучше не оставлять, засоряют проект

2022-07-07 17:10 UTC, podlovchenko commented on src/components/chatlist/ChatList.css
> +             background-color: #EDEFF1;
Цвета стоит вынести в css переменные, так будет понятнее, что это за цвет при чтении и проще изменять по всему проекту
https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties

2022-07-07 17:10 UTC, podlovchenko commented on babel.config.js
> +};
Этот файл не нужен, в parcel транспиляция включена по умолчанию

2022-07-07 17:10 UTC, podlovchenko commented on src/components/newChatModal/NewChatModal.css
> +}
Форматирование поползло, было бы здорово добавить в проект prettier

2022-07-07 17:10 UTC, podlovchenko commented on src/controllers/account/AccountController.ts
> +      });
Этот код повторяется в нескольких местах, стоит придерживаться принципа DRY и вынести это в отдельную функцию

2022-07-07 17:10 UTC, podlovchenko commented on src/controllers/account/AccountController.ts
> +        headers: {},
Зачем передавать пустой объект?

2022-07-07 17:10 UTC, podlovchenko commented on src/controllers/auth/AuthController.ts
> +        withCredentials: true,
Можно внести внутрь класса Client

2022-07-07 17:10 UTC, podlovchenko commented on src/controllers/chat/ChatController.ts
> +        return true;
Зачем передавать true и false, эти значения нигде не обрабатываются

2022-07-07 17:10 UTC, podlovchenko commented on src/controllers/message/MessageController.ts
> +      if (event.code === 1006) {
Здорово, что есть комментарий, еще лучше вынести магическое число в константу с названием что оно обозначает

2022-07-07 17:10 UTC, podlovchenko commented on src/core/client/Client.ts
> +      headers = headers || defaultHeaders;
```suggestion
      const { headers = defaultHeaders, method, data } = options;
```

2022-07-07 17:10 UTC, podlovchenko commented on src/core/client/Client.ts
> +      headers = headers || defaultHeaders;
Тип options определен как `Record<string, any> | null`, здесь ошибка типизации, нельзя деструктуризировать null

2022-07-07 17:10 UTC, podlovchenko commented on src/core/client/Client.ts
> +          if (xhr.status === 200) {
Положительный ответ не только со статусом 200 https://developer.mozilla.org/ru/docs/Web/HTTP/Status

2022-07-07 17:10 UTC, podlovchenko commented on src/core/route/Route.ts
> +      render(this._props.rootQuery, this._block);
Возвращение false никак не обрабатывается

2022-07-07 17:10 UTC, podlovchenko commented on src/pages/messages/Messages.ts
> +      }
```suggestion
      const userId = store.getState().currentUser.id ?? localStorage.getItem('userId');
```

2022-07-09 03:50 UTC, podlovchenko reviewed
Привет) Все места с `@ts-ignore` заменены, на `any`, это также плохая практика, так как разрешает присваивание или передачу любого типа (может привести к ошибкам в ходе выполнения кода)

2022-07-09 03:50 UTC, podlovchenko commented on src/controllers/account/AccountController.ts
> +        headers: false,
Почему false? Если headers нет, то и передавать ничего не нужно

2022-07-09 03:50 UTC, podlovchenko commented on src/components/newChatModal/NewChatModal.ts
> +      const formData: any = {};
Это сокращает количество строчек, но по сути ничего не меняет
У formData тип Record<string, string>

2022-07-09 03:50 UTC, podlovchenko commented on src/controllers/account/AccountController.ts
>        .catch((e) => {
Можно `.catch(errorHandler)`

2022-07-09 03:50 UTC, podlovchenko commented on src/controllers/chat/ChatController.ts
>        .then((e: TObj) => {
Что такое e? Ни по названию переменной, ни по типу это непонятно

2022-07-09 03:50 UTC, podlovchenko commented on src/core/client/Client.ts
> +          if (xhr.status >= 200 && xhr.status < 300) {
Если сервер ответил редиректом, то нам не нужно реджектить запрос

2022-07-09 03:50 UTC, podlovchenko commented on src/utils/wsEventCodes/WsEventCodes.ts
> +export const BAD_TLS_HANDSHAKE = 1015;
Все переменные, если они не используются в проекте, необязательно добавлять

2022-07-09 03:50 UTC, podlovchenko commented on src/utils/validate/Validate.ts
> +        const value = input ? input!.value.trim() : '';
input?.value.trim() ?? ''

2022-07-09 05:44 UTC, ionetek commented on src/controllers/account/AccountController.ts
> +        headers: false,
Привет! Если отправлю совсем без headers, то подгрузятся дефолтные headers. 
Вообще мне для загрузки аватарки нужно передавать content-type: 
multipart/form-data; boundary=----**WebKitFormBoundaryGdnApIBp8BTKUAfu**

Я так понимаю, что этот  content-type генерируется автоматически. Этого получается добиться, только если я передаю пустые headers {} или false.

Если передавать content-type: multipart/form-data; (Без boundary) то не получается отправить файл

2022-07-09 14:18 UTC, podlovchenko commented on src/controllers/account/AccountController.ts
> +        headers: false,
Дефолтные хедеры
https://github.com/ionetek/middle.messenger.praktikum.yandex/blob/sprint_3/src/core/client/Client.ts#L38
нужно ставить только в случае, если передаешь данные в формате JSON
Нужно добавить проверку на тип data и в зависимости от него добавлять 'Content-type': 'application/json; charset=UTF-8'
И определить типы для headers и data в IQueryOptions

2022-07-09 14:19 UTC, podlovchenko commented
Оставила комментарий https://github.com/ionetek/middle.messenger.praktikum.yandex/pull/6#discussion_r917273200

2022-07-10 07:53 UTC, ionetek commented on src/core/client/Client.ts
> +          if (xhr.status >= 200 && xhr.status < 300) {
Он будет реджектиться
`if (xhr.status >= 200 && xhr.status < 300) {
            resolve(resp);
          } else {
            reject(resp);
          }`

2022-07-10 14:54 UTC, podlovchenko approved these changes
Привет, работу принимаю)

2022-07-10 14:54 UTC, podlovchenko commented on src/controllers/account/AccountController.ts
> +
Остались пустые строки, было бы хорошо добавить [prettier](https://prettier.io/docs/en/install.html) в проект, чтобы  привести в порядок код

2022-07-10 15:03 UTC, ionetek commented on src/controllers/account/AccountController.ts
> +
Вера, спасибо огромное за крутейшее ревью! Очень доволен тем, насколько внимательно вы посмотрели мой код. Обязательно оставлю отзыв! ❤️

2022-07-10 15:03 UTC, merged